spring:
  redis:
    host: 192.168.30.32
    lettuce:
      pool:
        max-active: 200
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ournote
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    check-location: false
    url: jdbc:mysql://127.0.0.1:3306/ournote
    user: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: ournote
server:
  port: 8080

ignore:
  url:
    post:
      - /auth/login
      - /auth/register
    get:
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /swagger-resources
      - /v2/api-docs